import React from 'react'
import Xpedition from '../illustrations/Xpedition'
import Fox from '../illustrations/Fox'
import {FormattedMessage} from 'react-intl'



export const expeditions = {

  //special
  specialsescalada: {
    headerTitle: <FormattedMessage id='expeditions.specialescalada.titulo'/>,
    headerText: <FormattedMessage id='expeditions.specialescalada.bajada'/>,
    headerImage: require('../../images/expedition/escalada/header.jpg'),
    videoTitle: <FormattedMessage id='expeditions.specialescalada.video.titulo'/>,
    videoText: <FormattedMessage id='expeditions.specialescalada.video.bajada'/>,
    videoImage: require('../../images/expedition/escalada/video.jpg'),
    detailTitle: <FormattedMessage id='expeditions.specialescalada.detalle.titulo'/>,
    detailText: <FormattedMessage id='expeditions.specialescalada.detalle.bajada'/>,
    detailIllustration: Xpedition,
    deatilImage: require('../../images/expedition/escalada/detail.jpg'),
    detailCardText: <FormattedMessage id='expeditions.specialescalada.card.text'/>,
    icons: {
      walk: { oneWay: true, distance: '0,5', time: '30', unit: 'min' },
      vehicle: { distance: '4', time: '20', unit: 'min' },
      height: { start: '30', max: '30'},
    },
    sliderImages: [ 
      require('../../images/expedition/escalada/gallery/galeria1.jpg'), 
      require('../../images/expedition/escalada/gallery/galeria2.jpg'),
      require('../../images/expedition/escalada/gallery/galeria3.jpg'),
    ],
    videoH1: <FormattedMessage id='expeditions.titlevid'/>,
    videoCode: '0GKfU_A4wIc',
    videoCover: require('../../images/expedition/escalada/video.jpg'),
    downloads: [ { name: <FormattedMessage id="text.descargar"/>, link: '#' } ],
    downloadIllustration: Fox
  },
  specialsphotosafari: {
    headerTitle: <FormattedMessage id='expeditions.specialphotosafari.titulo'/>,
    headerText: <FormattedMessage id='expeditions.specialphotosafari.bajada'/>,
    headerImage: require('../../images/expedition/photo-safari/header.jpg'),
    videoTitle: <FormattedMessage id='expeditions.specialphotosafari.video.titulo'/>,
    videoText: <FormattedMessage id='expeditions.specialphotosafari.video.bajada'/>,
    videoImage: require('../../images/expedition/photo-safari/video.jpg'),
    detailTitle: <FormattedMessage id='expeditions.specialphotosafari.detalle.titulo'/>,
    detailText: <FormattedMessage id='expeditions.specialphotosafari.detalle.bajada'/>,
    detailIllustration: Xpedition,
    deatilImage: require('../../images/expedition/photo-safari/detail.jpg'),
    detailCardText: <FormattedMessage id='expeditions.specialphotosafari.card.text'/>,
    icons: {
      walk: { oneWay: true, distance: '7,5', time: '3' },
      vehicle: { distance: '141', time: '7'},
      height: { start: '30', max: '350'},
    },
    sliderImages: [ 
      require('../../images/expedition/photo-safari/gallery/galeria1.jpg'), 
      require('../../images/expedition/photo-safari/gallery/galeria2.jpg'),
      require('../../images/expedition/photo-safari/gallery/galeria3.jpg'),
    ],
    videoH1: <FormattedMessage id='expeditions.titlevid'/>,
    videoCode: 'ZvFAGP74odY',
    videoCover: require('../../images/expedition/photo-safari/video.jpg'),
    downloads: [ { name: <FormattedMessage id="text.descargar"/>, link: '#' } ],
    downloadIllustration: Fox
  },

  /// horse riding
  horseridingtwohours: {
    headerTitle: <FormattedMessage id='expeditions.horseridingtwohours.titulo'/>,
    headerText: <FormattedMessage id='expeditions.horseridingtwohours.bajada'/>,
    headerImage: require('../../images/expedition/cabalgata/header.jpg'),
    videoTitle: <FormattedMessage id='expeditions.horseridingtwohours.video.titulo'/>,
    videoText: <FormattedMessage id='expeditions.horseridingtwohours.video.bajada'/>,
    videoImage: require('../../images/expedition/cabalgata/video.jpg'),
    detailTitle: <FormattedMessage id='expeditions.horseridingtwohours.detalle.titulo'/>,
    detailText: <FormattedMessage id='expeditions.horseridingtwohours.detalle.bajada'/>,
    detailIllustration: Xpedition,
    deatilImage: require('../../images/expedition/cabalgata/detail.jpg'),
    detailCardText: <FormattedMessage id='expeditions.horseridingtwohours.card.text'/>,
    icons: {
      walk: { distance: '7', time: '1,5 - 2' },
      height: { start: '30', max: '30'},
    },
    sliderImages: [ 
      require('../../images/expedition/cabalgata/gallery/galeria1.jpg'), 
      require('../../images/expedition/cabalgata/gallery/galeria2.jpg'),
      require('../../images/expedition/cabalgata/gallery/galeria3.jpg'),
    ],
    videoH1: <FormattedMessage id='expeditions.titlevid'/>,
    videoCode: 'Z3YdEDKm7qo',
    videoCover: require('../../images/expedition/cabalgata/video.jpg'),
    downloads: [ { name: <FormattedMessage id="text.descargar"/>, link: '#' } ],
    downloadIllustration: Fox
  },

  horseridingpntp: {
    headerTitle: <FormattedMessage id='expeditions.horseridingpntp.titulo'/>,
    headerText: <FormattedMessage id='expeditions.horseridingpntp.bajada'/>,
    headerImage: require('../../images/expedition/cabalgata-pntp/header.jpg'),
    videoTitle: <FormattedMessage id='expeditions.horseridingpntp.video.titulo'/>,
    videoText: <FormattedMessage id='expeditions.horseridingpntp.video.bajada'/>,
    videoImage: require('../../images/expedition/cabalgata-pntp/video.jpg'),
    detailTitle: <FormattedMessage id='expeditions.horseridingpntp.detalle.titulo'/>,
    detailText: <FormattedMessage id='expeditions.horseridingpntp.detalle.bajada'/>,
    detailIllustration: Xpedition,
    deatilImage: require('../../images/expedition/cabalgata-pntp/detail.jpg'),
    detailCardText: <FormattedMessage id='expeditions.horseridingpntp.card.text'/>,
    sliderImages: [ 
      require('../../images/expedition/cabalgata-pntp/gallery/galeria1.jpg'), 
      require('../../images/expedition/cabalgata-pntp/gallery/galeria2.jpg'),
      require('../../images/expedition/cabalgata-pntp/gallery/galeria3.jpg'),
    ],
    videoH1: <FormattedMessage id='expeditions.titlevid'/>,
    videoCode: 'Z3YdEDKm7qo',
    videoCover: require('../../images/expedition/cabalgata-pntp/video.jpg'),
    downloads: [ { name: <FormattedMessage id="text.descargar"/>, link: '#' } ],
    downloadIllustration: Fox
  },
  


  /// hiking 

  trekkingbasetorres: {
    headerTitle: <FormattedMessage id='expeditions.trekkingbasetorres.titulo'/>,
    headerText: <FormattedMessage id='expeditions.trekkingbasetorres.bajada'/>,
    headerImage: require('../../images/expedition/base-torres/header.jpg'),
    videoTitle: <FormattedMessage id='expeditions.trekkingbasetorres.video.titulo'/>,
    videoText: <FormattedMessage id='expeditions.trekkingbasetorres.video.bajada'/>,
    videoImage: require('../../images/expedition/base-torres/video.jpg'),
    detailTitle: <FormattedMessage id='expeditions.trekkingbasetorres.detalle.titulo'/>,
    detailText: <FormattedMessage id='expeditions.trekkingbasetorres.detalle.bajada'/>,
    detailIllustration: Xpedition,
    deatilImage: require('../../images/expedition/base-torres/detail.jpg'),
    detailCardText: <FormattedMessage id='expeditions.trekkingbasetorres.card.text'/>,
    icons: {
      walk: { distance: '22', time: '8 - 9' },
      vehicle: { distance: '109', time: '3' },
      height: { start: '120', max: '875'},
    },
    sliderImages: [ 
      require('../../images/expedition/base-torres/gallery/galeria1.jpg'), 
      require('../../images/expedition/base-torres/gallery/galeria2.jpg'),
      require('../../images/expedition/base-torres/gallery/galeria3.jpg'),
    ],
    videoH1: <FormattedMessage id='expeditions.titlevid'/>,
    videoCode: 'bd6eafAAwR0',
    videoCover: require('../../images/expedition/base-torres/video.jpg'),
    downloads: [ { name: <FormattedMessage id="text.descargar"/>, link: '#' } ],
    downloadIllustration: Fox
  },
  trekkingcordonchacabuco: {
    headerTitle: <FormattedMessage id='expeditions.trekkingcordonchacabuco.titulo'/>,
    headerText: <FormattedMessage id='expeditions.trekkingcordonchacabuco.bajada'/>,
    headerImage: require('../../images/expedition/cordon-chacabuco/header.jpg'),
    videoTitle: <FormattedMessage id='expeditions.trekkingcordonchacabuco.video.titulo'/>,
    videoText: <FormattedMessage id='expeditions.trekkingcordonchacabuco.video.bajada'/>,
    videoImage: require('../../images/expedition/cordon-chacabuco/video.jpg'),
    detailTitle: <FormattedMessage id='expeditions.trekkingcordonchacabuco.detalle.titulo'/>,
    detailText: <FormattedMessage id='expeditions.trekkingcordonchacabuco.detalle.bajada'/>,
    detailIllustration: Xpedition,
    deatilImage: require('../../images/expedition/cordon-chacabuco/detail.jpg'),
    detailCardText: <FormattedMessage id='expeditions.trekkingcordonchacabuco.card.text'/>,
    icons: {
      walk: { distance: '7 - 8', time: '3' },
      height: { start: '26', max: '53'},
    },
    sliderImages: [ 
      require('../../images/expedition/cordon-chacabuco/gallery/galeria1.jpg'), 
      require('../../images/expedition/cordon-chacabuco/gallery/galeria2.jpg'),
      require('../../images/expedition/cordon-chacabuco/gallery/galeria3.jpg'),
    ],
    videoH1: <FormattedMessage id='expeditions.titlevid'/>,
    videoCode: 'HmlPcrTukbU',
    videoCover: require('../../images/expedition/cordon-chacabuco/video.jpg'),
    downloads: [ { name: <FormattedMessage id="text.descargar"/>, link: '#' } ],
    downloadIllustration: Fox
  },
  trekkingvallefrances: {
    headerTitle: <FormattedMessage id='expeditions.trekkingvallefrances.titulo'/>,
    headerText: <FormattedMessage id='expeditions.trekkingvallefrances.bajada'/>,
    headerImage: require('../../images/expedition/valle-frances/header.jpg'),
    videoTitle: <FormattedMessage id='expeditions.trekkingvallefrances.video.titulo'/>,
    videoText: <FormattedMessage id='expeditions.trekkingvallefrances.video.bajada'/>,
    videoImage: require('../../images/expedition/valle-frances/video.jpg'),
    detailTitle: <FormattedMessage id='expeditions.trekkingvallefrances.detalle.titulo'/>,
    detailText: <FormattedMessage id='expeditions.trekkingvallefrances.detalle.bajada'/>,
    detailIllustration: Xpedition,
    deatilImage: require('../../images/expedition/valle-frances/detail.jpg'),
    detailCardText: <FormattedMessage id='expeditions.trekkingvallefrances.card.text'/>,
    icons: {
      walk: { distance: '21', time: '7 - 8' },
      vehicle: { distance: '50', time: '1.5' },
      navigation: { distance: '21', time: '1' },
      height: { start: '65', max: '512'},
    },
    sliderImages: [ 
      require('../../images/expedition/valle-frances/gallery/galeria1.jpg'), 
      require('../../images/expedition/valle-frances/gallery/galeria2.jpg'),
      require('../../images/expedition/valle-frances/gallery/galeria3.jpg'),
    ],
    videoH1: <FormattedMessage id='expeditions.titlevid'/>,
    videoCode: 'fXyt5Hrl3-c',
    videoCover: require('../../images/expedition/valle-frances/video.jpg'),
    downloads: [ { name: <FormattedMessage id="text.descargar"/>, link: '#' } ],
    downloadIllustration: Fox
  },
  trekkingmiradorferrier: {
    headerTitle: <FormattedMessage id='expeditions.trekkingmiradorferrier.titulo'/>,
    headerText: <FormattedMessage id='expeditions.trekkingmiradorferrier.bajada'/>,
    headerImage: require('../../images/expedition/mirador-ferrier/header.jpg'),
    videoTitle: <FormattedMessage id='expeditions.trekkingmiradorferrier.video.titulo'/>,
    videoText: <FormattedMessage id='expeditions.trekkingmiradorferrier.video.bajada'/>,
    videoImage: require('../../images/expedition/mirador-ferrier/video.jpg'),
    detailTitle: <FormattedMessage id='expeditions.trekkingmiradorferrier.detalle.titulo'/>,
    detailText: <FormattedMessage id='expeditions.trekkingmiradorferrier.detalle.bajada'/>,
    detailIllustration: Xpedition,
    deatilImage: require('../../images/expedition/mirador-ferrier/detail.jpg'),
    detailCardText: <FormattedMessage id='expeditions.trekkingmiradorferrier.card.text'/>,
    icons: {
      walk: { distance: '6', time: '3 - 4' },
      vehicle: { distance: '54', time: '1,1' },
      height: { start: '60', max: '700'},
    },
    sliderImages: [ 
      require('../../images/expedition/mirador-ferrier/gallery/galeria1.jpg'), 
      require('../../images/expedition/mirador-ferrier/gallery/galeria2.jpg'),
      require('../../images/expedition/mirador-ferrier/gallery/galeria3.jpg'),
    ],
    videoH1: <FormattedMessage id='expeditions.titlevid'/>,
    videoCode: '97ttUlaUbUc',
    videoCover: require('../../images/expedition/mirador-ferrier/video.jpg'),
    downloads: [ { name: <FormattedMessage id="text.descargar"/>, link: '#' } ],
    downloadIllustration: Fox
  },
  trekkingchorrillopingo: {
    headerTitle: <FormattedMessage id='expeditions.trekkingchorrillopingo.titulo'/>,
    headerText: <FormattedMessage id='expeditions.trekkingchorrillopingo.bajada'/>,
    headerImage: require('../../images/expedition/pingo-chorrillo/header.jpg'),
    videoTitle: <FormattedMessage id='expeditions.trekkingchorrillopingo.video.titulo'/>,
    videoText: <FormattedMessage id='expeditions.trekkingchorrillopingo.video.bajada'/>,
    videoImage: require('../../images/expedition/pingo-chorrillo/video.jpg'),
    detailTitle: <FormattedMessage id='expeditions.trekkingchorrillopingo.detalle.titulo'/>,
    detailText: <FormattedMessage id='expeditions.trekkingchorrillopingo.detalle.bajada'/>,
    detailIllustration: Xpedition,
    deatilImage: require('../../images/expedition/pingo-chorrillo/detail.jpg'),
    detailCardText: <FormattedMessage id='expeditions.trekkingchorrillopingo.card.text'/>,
    icons: {
      walk: { distance: '8', time: '3 - 4' },
      vehicle: { distance: '54', time: '1,1' },
      height: { start: '60', max: '105'},
    },
    sliderImages: [ 
      require('../../images/expedition/pingo-chorrillo/gallery/galeria1.jpg'), 
      require('../../images/expedition/pingo-chorrillo/gallery/galeria2.jpg'),
      require('../../images/expedition/pingo-chorrillo/gallery/galeria3.jpg'),
    ],
    videoH1: <FormattedMessage id='expeditions.titlevid'/>,
    videoCode: 'wPvN5117IMY',
    videoCover: require('../../images/expedition/pingo-chorrillo/video.jpg'),
    downloads: [ { name: <FormattedMessage id="text.descargar"/>, link: '#' } ],
    downloadIllustration: Fox
  },
  trekkingcascadapingo: {
    headerTitle: <FormattedMessage id='expeditions.trekkingcascadapingo.titulo'/>,
    headerText: <FormattedMessage id='expeditions.trekkingcascadapingo.bajada'/>,
    headerImage: require('../../images/expedition/cascada-pingo/header.jpg'),
    videoTitle: <FormattedMessage id='expeditions.trekkingcascadapingo.video.titulo'/>,
    videoText: <FormattedMessage id='expeditions.trekkingcascadapingo.video.bajada'/>,
    videoImage: require('../../images/expedition/cascada-pingo/video.jpg'),
    detailTitle: <FormattedMessage id='expeditions.trekkingcascadapingo.detalle.titulo'/>,
    detailText: <FormattedMessage id='expeditions.trekkingcascadapingo.detalle.bajada'/>,
    detailIllustration: Xpedition,
    deatilImage: require('../../images/expedition/cascada-pingo/detail.jpg'),
    detailCardText: <FormattedMessage id='expeditions.trekkingcascadapingo.card.text'/>,
    
    sliderImages: [ 
      require('../../images/expedition/cascada-pingo/gallery/galeria1.jpg'), 
      require('../../images/expedition/cascada-pingo/gallery/galeria2.jpg'),
      require('../../images/expedition/cascada-pingo/gallery/galeria3.jpg'),
    ],
    video: ''
  },
  trekkingsaltoserrano: {
    headerTitle: <FormattedMessage id='expeditions.trekkingsaltoserrano.titulo'/>,
    headerText: <FormattedMessage id='expeditions.trekkingsaltoserrano.bajada'/>,
    headerImage: require('../../images/expedition/salto-serrano/header.jpg'),
    videoTitle: <FormattedMessage id='expeditions.trekkingsaltoserrano.video.titulo'/>,
    videoText: <FormattedMessage id='expeditions.trekkingsaltoserrano.video.bajada'/>,
    videoImage: require('../../images/expedition/salto-serrano/video.jpg'),
    detailTitle: <FormattedMessage id='expeditions.trekkingsaltoserrano.detalle.titulo'/>,
    detailText: <FormattedMessage id='expeditions.trekkingsaltoserrano.detalle.bajada'/>,
    detailIllustration: Xpedition,
    deatilImage: require('../../images/expedition/salto-serrano/detail.jpg'),
    detailCardText: <FormattedMessage id='expeditions.trekkingsaltoserrano.card.text'/>,
    sliderImages: [ 
      require('../../images/expedition/salto-serrano/gallery/galeria1.jpg'), 
      require('../../images/expedition/salto-serrano/gallery/galeria2.jpg'),
      require('../../images/expedition/salto-serrano/gallery/galeria3.jpg'),
    ],
    video: ''
  },
  trekkinglagunaescondida: {
    headerTitle: <FormattedMessage id='expeditions.trekkinglagunaescondida.titulo'/>,
    headerText: <FormattedMessage id='expeditions.trekkinglagunaescondida.bajada'/>,
    headerImage: require('../../images/expedition/laguna-escondida/header.jpg'),
    videoTitle: <FormattedMessage id='expeditions.trekkinglagunaescondida.video.titulo'/>,
    videoText: <FormattedMessage id='expeditions.trekkinglagunaescondida.video.bajada'/>,
    videoImage: require('../../images/expedition/laguna-escondida/video.jpg'),
    detailTitle: <FormattedMessage id='expeditions.trekkinglagunaescondida.detalle.titulo'/>,
    detailText: <FormattedMessage id='expeditions.trekkinglagunaescondida.detalle.bajada'/>,
    detailIllustration: Xpedition,
    deatilImage: require('../../images/expedition/laguna-escondida/detail.jpg'),
    detailCardText: <FormattedMessage id='expeditions.trekkinglagunaescondida.card.text'/>,
    icons: {
      walk: { distance: '6', time: '3' },
      height: { start: '30', max: '350'},
    },
    sliderImages: [ 
      require('../../images/expedition/laguna-escondida/gallery/galeria1.jpg'), 
      require('../../images/expedition/laguna-escondida/gallery/galeria2.jpg'),
      require('../../images/expedition/laguna-escondida/gallery/galeria3.jpg'),
    ],
    videoH1: <FormattedMessage id='expeditions.titlevid'/>,
    videoCode: 'hNxzg3rAkG8',
    videoCover: require('../../images/expedition/laguna-escondida/video.jpg'),
    downloads: [ { name: <FormattedMessage id="text.descargar"/>, link: '#' } ],
    downloadIllustration: Fox
  },
  trekkingmiradorcondor: {
    headerTitle: <FormattedMessage id='expeditions.trekkingmiradorcondor.titulo'/>,
    headerText: <FormattedMessage id='expeditions.trekkingmiradorcondor.bajada'/>,
    headerImage: require('../../images/expedition/mirador-condor/header.jpg'),
    videoTitle: <FormattedMessage id='expeditions.trekkingmiradorcondor.video.titulo'/>,
    videoText: <FormattedMessage id='expeditions.trekkingmiradorcondor.video.bajada'/>,
    videoImage: require('../../images/expedition/mirador-condor/video.jpg'),
    detailTitle: <FormattedMessage id='expeditions.trekkingmiradorcondor.detalle.titulo'/>,
    detailText: <FormattedMessage id='expeditions.trekkingmiradorcondor.detalle.bajada'/>,
    detailIllustration: Xpedition,
    deatilImage: require('../../images/expedition/mirador-condor/detail.jpg'),
    detailCardText: <FormattedMessage id='expeditions.trekkingmiradorcondor.card.text'/>,
    icons: {
      walk: { oneWay: true, distance: '4,5', time: '2,5' },
      vehicle: { distance: '41', time: '1,1' },
      height: { start: '70', max: '350'},
    },
    sliderImages: [ 
      require('../../images/expedition/mirador-condor/gallery/galeria1.jpg'), 
      require('../../images/expedition/mirador-condor/gallery/galeria2.jpg'),
      require('../../images/expedition/mirador-condor/gallery/galeria3.jpg'),
    ],
    videoH1: <FormattedMessage id='expeditions.titlevid'/>,
    videoCode: 'VEqZqjYrmj8',
    videoCover: require('../../images/expedition/mirador-condor/video.jpg'),
    downloads: [ { name: <FormattedMessage id="text.descargar"/>, link: '#' } ],
    downloadIllustration: Fox
  },
  trekkingmiradortoro: {
    headerTitle: <FormattedMessage id='expeditions.trekkingmiradortoro.titulo'/>,
    headerText: <FormattedMessage id='expeditions.trekkingmiradortoro.bajada'/>,
    headerImage: require('../../images/expedition/mirador-toro/header.jpg'),
    videoTitle: <FormattedMessage id='expeditions.trekkingmiradortoro.video.titulo'/>,
    videoText: <FormattedMessage id='expeditions.trekkingmiradortoro.video.bajada'/>,
    videoImage: require('../../images/expedition/mirador-toro/video.jpg'),
    detailTitle: <FormattedMessage id='expeditions.trekkingmiradortoro.detalle.titulo'/>,
    detailText: <FormattedMessage id='expeditions.trekkingmiradortoro.detalle.bajada'/>,
    detailIllustration: Xpedition,
    deatilImage: require('../../images/expedition/mirador-toro/detail.jpg'),
    detailCardText: <FormattedMessage id='expeditions.trekkingmiradortoro.card.text'/>,
    icons: {
      walk: { distance: '5,5', time: '2,5 - 3' },
      vehicle: { distance: '22', time: '40', unit: 'min' },
      height: { start: '50', max: '400'},
    },
    sliderImages: [ 
      require('../../images/expedition/mirador-toro/gallery/galeria1.jpg'), 
      require('../../images/expedition/mirador-toro/gallery/galeria2.jpg'),
      require('../../images/expedition/mirador-toro/gallery/galeria3.jpg'),
    ],
    videoH1: <FormattedMessage id='expeditions.titlevid'/>,
    videoCode: 'v9Bby8o18og',
    videoCover: require('../../images/expedition/mirador-toro/video.jpg'),
    downloads: [ { name: <FormattedMessage id="text.descargar"/>, link: '#' } ],
    downloadIllustration: Fox
  },
  trekkingmiradorcuernos: {
    headerTitle: <FormattedMessage id='expeditions.trekkingmiradorcuernos.titulo'/>,
    headerText: <FormattedMessage id='expeditions.trekkingmiradorcuernos.bajada'/>,
    headerImage: require('../../images/expedition/mirador-cuernos/header.jpg'),
    videoTitle: <FormattedMessage id='expeditions.trekkingmiradorcuernos.video.titulo'/>,
    videoText: <FormattedMessage id='expeditions.trekkingmiradorcuernos.video.bajada'/>,
    videoImage: require('../../images/expedition/mirador-cuernos/video.jpg'),
    detailTitle: <FormattedMessage id='expeditions.trekkingmiradorcuernos.detalle.titulo'/>,
    detailText: <FormattedMessage id='expeditions.trekkingmiradorcuernos.detalle.bajada'/>,
    detailIllustration: Xpedition,
    deatilImage: require('../../images/expedition/mirador-cuernos/detail.jpg'),
    detailCardText: <FormattedMessage id='expeditions.trekkingmiradorcuernos.card.text'/>,
    icons: {
      walk: { distance: '6,5', time: '2 - 2,5' },
      vehicle: { distance: '51', time: '1,5' },
      height: { start: '60', max: '177'},
    },
    sliderImages: [ 
      require('../../images/expedition/mirador-cuernos/gallery/galeria1.jpg'), 
      require('../../images/expedition/mirador-cuernos/gallery/galeria2.jpg'),
      require('../../images/expedition/mirador-cuernos/gallery/galeria3.jpg'),
    ],
    videoH1: <FormattedMessage id='expeditions.titlevid'/>,
    videoCode: 'Io_ARiD4uRQ',
    videoCover: require('../../images/expedition/mirador-cuernos/video.jpg'),
    downloads: [ { name: <FormattedMessage id="text.descargar"/>, link: '#' } ],
    downloadIllustration: Fox
  },
  trekkingaonikenk: {
    headerTitle: <FormattedMessage id='expeditions.trekkingaonikenk.titulo'/>,
    headerText: <FormattedMessage id='expeditions.trekkingaonikenk.bajada'/>,
    headerImage: require('../../images/expedition/aonikenk/header.jpg'),
    videoTitle: <FormattedMessage id='expeditions.trekkingaonikenk.video.titulo'/>,
    videoText: <FormattedMessage id='expeditions.trekkingaonikenk.video.bajada'/>,
    videoImage: require('../../images/expedition/aonikenk/video.jpg'),
    detailTitle: <FormattedMessage id='expeditions.trekkingaonikenk.detalle.titulo'/>,
    detailText: <FormattedMessage id='expeditions.trekkingaonikenk.detalle.bajada'/>,
    detailIllustration: Xpedition,
    deatilImage: require('../../images/expedition/aonikenk/detail.jpg'),
    detailCardText: <FormattedMessage id='expeditions.trekkingaonikenk.card.text'/>,
    icons: {
      walk: { oneWay: true, distance: '6,5', time: '2,5' },
      vehicle: { distance: '84', time: '2' },
      height: { start: '70', max: '350'},
    },
    sliderImages: [ 
      require('../../images/expedition/aonikenk/gallery/galeria1.jpg'), 
      require('../../images/expedition/aonikenk/gallery/galeria2.jpg'),
      require('../../images/expedition/aonikenk/gallery/galeria3.jpg'),
    ],
    videoH1: <FormattedMessage id='expeditions.titlevid'/>,
    videoCode: 'xg6daXzfUjo',
    videoCover: require('../../images/expedition/aonikenk/video.jpg'),
    downloads: [ { name: <FormattedMessage id="text.descargar"/>, link: '#' } ],
    downloadIllustration: Fox
  },
  trekkingplayasarmiento: {
    headerTitle: <FormattedMessage id='expeditions.trekkingplayasarmiento.titulo'/>,
    headerText: <FormattedMessage id='expeditions.trekkingplayasarmiento.bajada'/>,
    headerImage: require('../../images/expedition/sarmiento/header.jpg'),
    videoTitle: <FormattedMessage id='expeditions.trekkingplayasarmiento.video.titulo'/>,
    videoText: <FormattedMessage id='expeditions.trekkingplayasarmiento.video.bajada'/>,
    videoImage: require('../../images/expedition/sarmiento/video.jpg'),
    detailTitle: <FormattedMessage id='expeditions.trekkingplayasarmiento.detalle.titulo'/>,
    detailIllustration: Xpedition,
    detailText: <FormattedMessage id='expeditions.trekkingplayasarmiento.detalle.bajada'/>,
    deatilImage: require('../../images/expedition/sarmiento/detail.jpg'),
    detailCardText: <FormattedMessage id='expeditions.trekkingplayasarmiento.card.text'/>,
    icons: {
      walk: { distance: '5', time: '2 - 2,5' },
      vehicle: { distance: '65', time: '1,2' },
      height: { start: '125', max: '125'},
    },
    sliderImages: [ 
      require('../../images/expedition/sarmiento/gallery/galeria1.jpg'), 
      require('../../images/expedition/sarmiento/gallery/galeria2.jpg'),
      require('../../images/expedition/sarmiento/gallery/galeria3.jpg'),
    ],
    videoH1: <FormattedMessage id='expeditions.titlevid'/>,
    videoCode: 'NLZtg018h0E',
    videoCover: require('../../images/expedition/sarmiento/video.jpg'),
    downloads: [ { name: <FormattedMessage id="text.descargar"/>, link: '#' } ],
    downloadIllustration: Fox
  },
  trekkingsenderogrey: {
    headerTitle: <FormattedMessage id='expeditions.trekkingsenderogrey.titulo'/>,
    headerText: <FormattedMessage id='expeditions.trekkingsenderogrey.bajada'/>,
    headerImage: require('../../images/expedition/sendero-glaciar-grey/header.jpg'),
    videoTitle: <FormattedMessage id='expeditions.trekkingsenderogrey.video.titulo'/>,
    videoText: <FormattedMessage id='expeditions.trekkingsenderogrey.video.bajada'/>,
    videoImage: require('../../images/fondo_2.jpg'),
    detailTitle: <FormattedMessage id='expeditions.trekkingsenderogrey.detalle.titulo'/>,
    detailText: <FormattedMessage id='expeditions.trekkingsenderogrey.detalle.bajada'/>,
    detailIllustration: Xpedition,
    deatilImage: require('../../images/expedition/sendero-glaciar-grey/detail.jpg'),
    detailCardText: <FormattedMessage id='expeditions.trekkingsenderogrey.card.text'/>,
    icons: {
      walk: { distance: '22', time: '7 - 8' },
      vehicle: { distance: '50', time: '1.5' },
      navigation: { distance: '21', time: '1' },
      height: { start: '65', max: '450'},
    },
    sliderImages: [ 
      require('../../images/expedition/sendero-glaciar-grey/gallery/galeria1.jpg'), 
      require('../../images/expedition/sendero-glaciar-grey/gallery/galeria2.jpg'),
      require('../../images/expedition/sendero-glaciar-grey/gallery/galeria3.jpg'),
    ],
    videoH1: <FormattedMessage id='expeditions.titlevid'/>,
    videoCode: 'iJDBHhfhdSI',
    videoCover: require('../../images/expedition/sendero-glaciar-grey/video.jpg'),
    downloads: [ { name: <FormattedMessage id="text.descargar"/>, link: '#' } ],
    downloadIllustration: Fox
  },
  trekkingsenderocuernos: {
    headerTitle: <FormattedMessage id='expeditions.trekkingsenderocuernos.titulo'/>,
    headerText: <FormattedMessage id='expeditions.trekkingsenderocuernos.bajada'/>,
    headerImage: require('../../images/expedition/sendero-cuernos/header.jpg'),
    videoTitle: <FormattedMessage id='expeditions.trekkingsenderocuernos.video.titulo'/>,
    videoText: <FormattedMessage id='expeditions.trekkingsenderocuernos.video.bajada'/>,
    videoImage: require('../../images/expedition/sendero-cuernos/video.jpg'),
    detailTitle: <FormattedMessage id='expeditions.trekkingsenderocuernos.detalle.titulo'/>,
    detailText: <FormattedMessage id='expeditions.trekkingsenderocuernos.detalle.bajada'/>,
    detailIllustration: Xpedition,
    deatilImage: require('../../images/expedition/sendero-cuernos/detail.jpg'),
    detailCardText: <FormattedMessage id='expeditions.trekkingsenderocuernos.card.text'/>,
    icons: {
      walk: { distance: '19', time: '7 - 8' },
      vehicle: { distance: '109', time: '3' },
      height: { start: '120', max: '330'},
    },
    sliderImages: [ 
      require('../../images/expedition/sendero-cuernos/gallery/galeria1.jpg'), 
      require('../../images/expedition/sendero-cuernos/gallery/galeria2.jpg'),
      require('../../images/expedition/sendero-cuernos/gallery/galeria3.jpg'),
    ],
    videoH1: <FormattedMessage id='expeditions.titlevid'/>,
    videoCode: '9oKkY7X_3bM',
    videoCover: require('../../images/expedition/sendero-cuernos/video.jpg'),
    downloads: [ { name: <FormattedMessage id="text.descargar"/>, link: '#' } ],
    downloadIllustration: Fox
  },
  trekkingcampoesmeralda: {
    headerTitle: <FormattedMessage id='expeditions.trekkingcampoesmeralda.titulo'/>,
    headerText: <FormattedMessage id='expeditions.trekkingcampoesmeralda.bajada'/>,
    headerImage: require('../../images/expedition/campo-esmeralda/header.jpg'),
    videoTitle: <FormattedMessage id='expeditions.trekkingcampoesmeralda.video.titulo'/>,
    videoText: <FormattedMessage id='expeditions.trekkingcampoesmeralda.video.bajada'/>,
    videoImage: require('../../images/expedition/campo-esmeralda/video.jpg'),
    detailTitle: <FormattedMessage id='expeditions.trekkingcampoesmeralda.detalle.titulo'/>,
    detailText: <FormattedMessage id='expeditions.trekkingcampoesmeralda.detalle.bajada'/>,
    detailIllustration: Xpedition,
    deatilImage: require('../../images/expedition/campo-esmeralda/detail.jpg'),
    detailCardText: <FormattedMessage id='expeditions.trekkingcampoesmeralda.card.text'/>,
    icons: {
      walk: { distance: '4', time: '2,5' },
      navigation: { distance: '16', time: '40', unit: 'min' },
      height: { start: '16', max: '59'},
    },
    sliderImages: [ 
      require('../../images/expedition/campo-esmeralda/gallery/galeria1.jpg'), 
      require('../../images/expedition/campo-esmeralda/gallery/galeria2.jpg'),
      require('../../images/expedition/campo-esmeralda/gallery/galeria3.jpg'),
    ],
    videoH1: <FormattedMessage id='expeditions.titlevid'/>,
    videoCode: '9piac8QYrv4',
    videoCover: require('../../images/expedition/campo-esmeralda/video.jpg'),
    downloads: [ { name: <FormattedMessage id="text.descargar"/>, link: '#' } ],
    downloadIllustration: Fox
  },
  trekkinglazoweber: {
    headerTitle: <FormattedMessage id='expeditions.trekkinglazoweber.titulo'/>,
    headerText: <FormattedMessage id='expeditions.trekkinglazoweber.bajada'/>,
    headerImage: require('../../images/expedition/lazoweber/header.jpg'),
    videoTitle: <FormattedMessage id='expeditions.trekkinglazoweber.video.titulo'/>,
    videoText: <FormattedMessage id='expeditions.trekkinglazoweber.video.bajada'/>,
    videoImage: require('../../images/expedition/lazoweber/video.jpg'),
    detailTitle: <FormattedMessage id='expeditions.trekkinglazoweber.detalle.titulo'/>,
    detailText: <FormattedMessage id='expeditions.trekkinglazoweber.detalle.bajada'/>,
    detailIllustration: Xpedition,
    deatilImage: require('../../images/expedition/lazoweber/detail.jpg'),
    detailCardText: <FormattedMessage id='expeditions.trekkinglazoweber.card.text'/>,
    icons: {
      walk: { oneWay: true, distance: '15', time: '5 - 6' },
      vehicle: { distance: '131', time: '2,2' },
      height: { start: '26', max: '414'},
    },
    sliderImages: [ 
      require('../../images/expedition/lazoweber/gallery/galeria1.jpg'), 
      require('../../images/expedition/lazoweber/gallery/galeria2.jpg'),
      require('../../images/expedition/lazoweber/gallery/galeria3.jpg'),
    ],
    videoH1: <FormattedMessage id='expeditions.titlevid'/>,
    videoCode: '9piac8QYrv4',
    videoCover: require('../../images/expedition/lazoweber/video.jpg'),
    downloads: [ { name: <FormattedMessage id="text.descargar"/>, link: '#' } ],
    downloadIllustration: Fox
  },



  // navegacion
  navigationsglaciargrey: {
    headerTitle: <FormattedMessage id='expeditions.navigationsglaciargrey.titulo'/>,
    headerText: <FormattedMessage id='expeditions.navigationsglaciargrey.bajada'/>,
    headerImage: require('../../images/expedition/navegacion-grey/header.jpg'),
    videoTitle: <FormattedMessage id='expeditions.navigationsglaciargrey.video.titulo'/>,
    videoText: <FormattedMessage id='expeditions.navigationsglaciargrey.video.bajada'/>,
    videoImage: require('../../images/expedition/navegacion-grey/video.jpg'),
    detailTitle: <FormattedMessage id='expeditions.navigationsglaciargrey.detalle.titulo'/>,
    detailText: <FormattedMessage id='expeditions.navigationsglaciargrey.detalle.bajada'/>,
    detailIllustration: Xpedition,
    deatilImage: require('../../images/expedition/navegacion-grey/detail.jpg'),
    detailCardText: <FormattedMessage id='expeditions.navigationsglaciargrey.card.text'/>,
    icons: {
      walk: { distance: '3', time: '1,5 - 2' },
      vehicle: { distance: '54', time: '1,1' },
      navigation: { distance: '41', time: '2,5 - 3' },
      height: { start: '60', max: '60'},
    },
    sliderImages: [ 
      require('../../images/expedition/navegacion-grey/gallery/galeria1.jpg'), 
      require('../../images/expedition/navegacion-grey/gallery/galeria2.jpg'),
      require('../../images/expedition/navegacion-grey/gallery/galeria3.jpg'),
    ],
    videoH1: <FormattedMessage id='expeditions.titlevid'/>,
    videoCode: '_LHCr_iBpF8',
    videoCover: require('../../images/expedition/navegacion-grey/video.jpg'),
    downloads: [ { name: <FormattedMessage id="text.descargar"/>, link: '#' } ],
    downloadIllustration: Fox
  },
  navigationsrioserrano: {
    headerTitle: <FormattedMessage id='expeditions.navigationsrioserrano.titulo'/>,
    headerText: <FormattedMessage id='expeditions.navigationsrioserrano.bajada'/>,
    headerImage: require('../../images/expedition/navegacion-serrano-boat/header.jpg'),
    videoTitle: <FormattedMessage id='expeditions.navigationsrioserrano.video.titulo'/>,
    videoText: <FormattedMessage id='expeditions.navigationsrioserrano.video.bajada'/>,
    videoImage: require('../../images/expedition/navegacion-serrano-boat/video.jpg'),
    detailTitle: <FormattedMessage id='expeditions.navigationsrioserrano.detalle.titulo'/>,
    detailText: <FormattedMessage id='expeditions.navigationsrioserrano.detalle.bajada'/>,
    detailIllustration: Xpedition,
    deatilImage: require('../../images/expedition/navegacion-serrano-boat/detail.jpg'),
    detailCardText: <FormattedMessage id='expeditions.navigationsrioserrano.card.text'/>,
    icons: {
      walk: { distance: '0,5', time: '45', unit: 'min' },
      navigation: { distance: '16,5', time: '40', unit: 'min' },
      height: { start: '16', max: '50'},
    },
    sliderImages: [ 
      require('../../images/expedition/navegacion-serrano-boat/gallery/galeria1.jpg'), 
      require('../../images/expedition/navegacion-serrano-boat/gallery/galeria2.jpg'),
      require('../../images/expedition/navegacion-serrano-boat/gallery/galeria3.jpg'),
    ],
    videoH1: <FormattedMessage id='expeditions.titlevid'/>,
    videoCode: 'GdutHeNd_YM',
    videoCover: require('../../images/expedition/navegacion-serrano-boat/video.jpg'),
    downloads: [ { name: <FormattedMessage id="text.descargar"/>, link: '#' } ],
    downloadIllustration: Fox
  },

  //fyll day
  fulldaypaine: {
    headerTitle: <FormattedMessage id='expeditions.fulldaypaine.titulo'/>,
    headerText: <FormattedMessage id='expeditions.fulldaypaine.bajada'/>,
    headerImage: require('../../images/expedition/full-day-paine/header.jpg'),
    videoTitle: <FormattedMessage id='expeditions.fulldaypaine.video.titulo'/>,
    videoText: <FormattedMessage id='expeditions.fulldaypaine.video.bajada'/>,
    videoImage: require('../../images/expedition/full-day-paine/video.jpg'),
    detailTitle: <FormattedMessage id='expeditions.fulldaypaine.detalle.titulo'/>,
    detailText: <FormattedMessage id='expeditions.fulldaypaine.detalle.bajada'/>,
    detailIllustration: Xpedition,
    deatilImage: require('../../images/expedition/full-day-paine/detail.jpg'),
    detailCardText: <FormattedMessage id='expeditions.fulldaypaine.card.text'/>,
    icons: {
      walk: { distance: '3', time: '1,5 - 2' },
      vehicle: { distance: '182', time: '6' },
      height: { start: '60', max: '60'},
    },
    sliderImages: [ 
      require('../../images/expedition/full-day-paine/gallery/galeria1.jpg'), 
      require('../../images/expedition/full-day-paine/gallery/galeria2.jpg'),
      require('../../images/expedition/full-day-paine/gallery/galeria3.jpg'),
    ],
    videoH1: <FormattedMessage id='expeditions.titlevid'/>,
    videoCode: 'SIMOqtLA57A',
    videoCover:require('../../images/expedition/full-day-paine/video.jpg'),
    downloads: [ { name: <FormattedMessage id="text.descargar"/>, link: '#' } ],
    downloadIllustration: Fox
  },
}